version: '2'
services: 
  web: 
    build: "."
    container_name: las_web_1
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports: 
      - "8090:80"
    restart: always
    volumes: 
      - "./www:/var/www/html/"
    networks:
      default:
        ipv4_address: 172.19.0.5
  redis:
    image: redis
    container_name: las_redis_1
    restart: always
    ports:
        - 6380:6379 
    volumes:
      - "./redis4:/data"
    networks:
      default:
        ipv4_address: 172.19.0.3
  phpmyadmin:
    build:
      context: .
      dockerfile: ./DockerfilePhpAdmin
    container_name: las_phpmyadmin_1
    restart: always
    links:
      - db
    ports:
      - 8092:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - "./schema/phpmyadmin/config.user.inc.php:/www/config.user.inc.php"
    networks:
      default:
        ipv4_address: 172.19.0.4
  db:
    build:
      context: .
      dockerfile: ./DockerfileSql
    container_name: las_db_1
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    networks:
      default:
        ipv4_address: 172.19.0.2
  #reactjs:
  #  image:  deredy/react-native
  #  container_name: react_1
  #  container_name: docker-react-native
  #  restart: always
  #  links:
  #    - db
  #    - redis
  #    - web
  #  volumes:
  #    - "./app:/app"
  #  networks:
  #    default:
  #      ipv4_address: 172.19.0.5
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
    #command: "sh ~/.data/scripts/permissions.sh"
