version: '2'
services: 
  web: 
    build: "."
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports: 
      - "8090:80"
    restart: always
    volumes: 
      - "~/.data/www:/var/www/html/"
  db:
    image: mysql:5.7
    container_name: db_1
    volumes:
      - "~/.data/db:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: dev123
       MYSQL_DATABASE: test
       MYSQL_USER: dev
       MYSQL_PASSWORD: dev123
  redis:
    image: redis    
    ports:
        - 6380:6379 
    volumes:
      - "~/.data/redis4:/data"
  phpmyadmin:
    build:
      context: .
      dockerfile: ./DockerfilePhpAdmin
    restart: always
    links:
      - db
    ports:
      - 8092:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - "~/.data/schema/phpmyadmin/config.user.inc.php:/www/config.user.inc.php"
  reactjs:
    image:  deredy/react-native
    container_name: docker-react-native
    restart: always
    links: 
      - db
      - redis
      - web
    volumes:
      - "~/.data/app:/app"
    #command: "sh ~/.data/scripts/permissions.sh"
