version: '2'
services: 
  web: 
    build: "."
    container_name: las_web_1
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports: 
      - "${WEB_PORT}:80"
    restart: always
    volumes: 
      - "${WEB_FOLDER}:/var/www/html/"
      - "${WEB_APACHE_CONF}:/etc/apache2/sites-available/sites.conf"
    networks:
      default:
        ipv4_address: 172.19.0.5
  redis:
    image: redis
    container_name: las_redis_1
    restart: always
    ports:
        - ${REDIS_PORT}:6379
    volumes:
      - "${REDIS_FOLDER}:/data"
    networks:
      default:
        ipv4_address: 172.19.0.3
  phpmyadmin:
    build:
      context: .
      dockerfile: ./DockerfilePhpAdmin
    container_name: las_phpmyadmin_1
    restart: always
    links:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - "${PHPMYADMIN_CONFIG}:/www/config.user.inc.php"
    networks:
      default:
        ipv4_address: 172.19.0.4
  db:
    build:
      context: .
      dockerfile: ./DockerfileSql
    container_name: las_db_1
    volumes:
      - "${DB_FOLDER}./db:/var/lib/mysql"
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      default:
        ipv4_address: 172.19.0.2
  portainer:
    image: portainer/portainer
    container_name: portain
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.19.0.6
  #reactjs:
  #  image:  deredy/react-native
  #  container_name: react_1
  #  container_name: docker-react-native
  #  restart: always
  #  links:
  #    - db
  #    - redis
  #    - web
  #  volumes:
  #    - "./app:/app"
  #  networks:
  #    default:
  #      ipv4_address: 172.19.0.5
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
    #command: "sh ~/.data/scripts/permissions.sh"
